### ISSUE TITLE
再请教下多图层图表语法如何写？

### ISSUE THREAD

**Issue by sherjf** [caronchen/obsidian-chartsview-plugin#3]
参考官方模板和API写，无法显示，不知什么原因？
```
type: Mix
data: 
- year: 2000
   value: 100
- year: 2010
   value: 150
plots:
- type: 'bar'
  region:
    start: {x: 0, y: 0}
    end: {x: 1, y: 1}
  options:
    xField: value
    yField: year
```
