### ISSUE TITLE
What is the syntax for configuring line style in mix?

### ISSUE THREAD

**Issue by Borouch** [caronchen/obsidian-chartsview-plugin#31]
On the Mix chart example that you provide we config our line like this:
```
options.line:
  axes: false
  geometries:
    - type: 'line'
      xField: 'time'
      yField: 'temperature'
      mapping: {}
```

Based on my reading of examples and Ant documentation, style should be configured like this:

```
options.line:
  axes: false
  geometries:
    - type: 'line'
      xField: 'time'
      yField: 'temperature'
      style:
        color: 'red'
      mapping: {}
```

Sadly I can't get it to work.  I hope you can illuminate where my ignorance lies with this basic question as I am sure it would be helpful for others like me.
