### ISSUE TITLE
Chart does not render inside column

### ISSUE THREAD

**Issue by Nedreow** [caronchen/obsidian-chartsview-plugin#40]
I'm trying to display 2 charts next to each other using https://github.com/tnichols217/obsidian-columns.

``````
```chart
type: pie
labels: [Filled,Empty]
series:
  - title: Title 1
    data: [1, 11]
width: 40%
labelColors: true
legend: false
```

`````col
````col-md
flexGrow=1
===
test error
```chart
type: pie
labels: [Filled,Empty]
series:
  - title: Title 1
     data: [1, 11]
width: 40%
labelColors: true
legend: false
```
````

````col-md
flexGrow=1
===
test valid
```chart
type: pie
labels: [Filled,Empty]
series:
  - title: Title 1
    data: [1, 11]
width: 40%
labelColors: true
legend: false
```
````
`````
``````
renders as:
![Charts side by side](https://user-images.githubusercontent.com/9559930/184965547-f3054aa0-dc60-4e02-94f5-2870fa3d0210.PNG)
