### ISSUE TITLE
Open file instead of open search 

### ISSUE THREAD

**Issue by Crownburger** [caronchen/obsidian-chartsview-plugin#44]
Is it possible to click on an item in the word cloud and directly open the coresponding file instead of opening the search?

Here is my code:
```
#-----------------#
#- chart type    -#
#-----------------#
type: WordCloud

#-----------------#
#- chart data    -#
#-----------------#
data: |
  dataviewjs:
  return dv.pages('"MOC" or "Notizen"')
           .sort(s => s.file.inlinks.length+s.file.outlinks.length, 'desc') 
           .map(p => ({notiz: p.file.name, count: p.file.inlinks.length+p.file.outlinks.length}))
           .array();

#-----------------#
#- chart options -#
#-----------------#
options:
  height: 150
  wordField: "notiz"
  weightField: "count"
  colorField: ""
  wordStyle:
    rotation: 0
    fontSize: [8,30]
  enableSearchInteraction: 
    field: 'word'
    operator: 'file'
```

Would be a huge plus for me if this would be possible!!
