### ISSUE TITLE
How to combine DualAxes with Dataview.js?

### ISSUE THREAD

**Issue by tauren** [caronchen/obsidian-chartsview-plugin#49]
I can't seem to get the combination of DualAxes and Dataview.js working. I'm not sure if I just have the syntax wrong, or if it doesn't work.

In the example below, I'm trying to have `data[0]` use dataview and `data[1]` be hard-coded just as an experiment. Ideally, I would only have one dataview query, but I need to mess around with the dataview API further to output the right structure.

```
type: DualAxes
data: 
  - |
    dataviewjs:
    return dv.pages()
           .groupBy(p => p.file.folder)
           .map(p => ({time: p.key || "ROOT", count: p.rows.length, value: 15}))
           .array();
  -
    - time: "2019-03"
      value: 350
      count: 800
    - time: "2019-04"
      value: 900
      count: 600
    - time: "2019-05"
      value: 300
      count: 400
    - time: "2019-06"
      value: 450
      count: 380
    - time: "2019-07"
      value: 470
      count: 22
 options:
  xField: 'time'
  yField: ['value', 'count']
  yAxis:
    value:
      min: 0
  geometryOptions:
    - geometry: 'column'
    - geometry: 'line'
      lineStyle:
        lineWidth: 2
```

This results in an error:

```
组件出错了，请核查后重试： r.filter is not a function
```
